version: "0.5"

processes:
  ecto_setup:
    namespace: "init"
    command: "mix ecto.setup"
    depends_on:
      postgresql:
        condition: process_launched
  phoenix_server:
    command: "mix phx.server"
    depends_on:
      ecto_setup:
        condition: process_completed
    availability:
      restart: "always"
