version: "0.5"

processes:
  restore_npm_packages:
    namespace: "init"
    command: "npm install"
  npm_start:
    command: "npm start"
    depends_on:
      restore_npm_packages:
        condition: process_completed
    availability:
      restart: "always"
